# Generated by Django 5.1.5 on 2025-04-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='Черновик'),
        ),
    ]
